# Generated by Django 3.1.4 on 2020-12-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
